import shutil
import zipfile
from pathlib import Path
from typing import Final

OVERLAY_PREFIX: Final[str] = "x2loc_zh_"


def overlay_mod_name(workshop_id: str) -> str:
    return f"{OVERLAY_PREFIX}{workshop_id}"


def _manifest(workshop_id: str, title: str) -> str:
    return (
        "[mod]\n"
        "publishedFileId=0\n"
        f"Title={title} [zh_Hans]\n"
        f"Description=Simplified Chinese localization of Workshop item "
        f"{workshop_id}, generated by x2loc.\n"
        "RequiresXPACK=true\n"
    )


def install_overlay(
    *, artifact: Path, mods_dir: Path, workshop_id: str, title: str
) -> Path:
    """Unpack a translated overlay zip as a standalone local mod.

    The translation lives in its own mod folder, so a Steam update of the
    source mod cannot overwrite it. The folder is assembled next to its
    final location and swapped in whole, so the game never sees a partial
    install; a re-run replaces the previous one.

    Args:
        artifact: Overlay zip built by the job pipeline.
        mods_dir: The game's `XComGame/Mods` directory; must already exist.
        workshop_id: Workshop id of the translated mod.
        title: Title of the translated mod, reused in the manifest.

    Returns:
        The installed mod folder.

    Raises:
        FileNotFoundError: If `mods_dir` does not exist.
    """
    name = overlay_mod_name(workshop_id)
    target = mods_dir / name
    staging = mods_dir / f".{name}.part"
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir()
    try:
        with zipfile.ZipFile(artifact) as archive:
            archive.extractall(staging)
        (staging / f"{name}.XComMod").write_text(
            _manifest(workshop_id, title), encoding="utf-8"
        )
        if target.exists():
            shutil.rmtree(target)
        staging.rename(target)
    finally:
        if staging.exists():
            shutil.rmtree(staging)
    return target
